name = "all-star-cleaning"
main = "./dist/_worker.js/index.js"
compatibility_date = "2026-05-07"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true
